import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner"


const jakarta = Plus_Jakarta_Sans({
  variable: "--font-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Providers } from "@/components/Providers"
import { TopBar } from "@/components/layout/TopBar"

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      className={`${jakarta.variable} h-full antialiased bg-slate-50/70 text-slate-900 font-sans`}
    >
      <body className="min-h-full flex flex-col">
        <Providers>
          <TopBar />
          {children}
        </Providers>
        <Toaster />
      </body>
    </html>
  );
}
